apiVersion: v1
kind: Service
metadata:
  name: durable-functions-service
  namespace: edgraph
spec:
  selector:
    app: durable-functions-pod

  ports:
  - port: 8080
    targetPort: 80
  type: LoadBalancer

